import { useEffect } from 'react';
import Head from 'next/head';
import getConfig from 'next/config';

import ProductDetail from '../components/ProductDetail';

import useLocalData from '../hooks/useLocalData';

const { publicRuntimeConfig } = getConfig();

declare interface ProductPageProps {
  product: IProduct;
}

function ProductPage(props: ProductPageProps) {
  const { product } = props || {};
  const { dispatch } = useLocalData();

  useEffect(() => {

    dispatch({
      name: 'header',
      type: 'update',
      value: {
        title: 'Accessories',
        titleLink: '/',
        subtitle: product.name
      }
    });
  }, [dispatch, product.name]);

  return (
    <>
      <Head>
        <title>{product.name} - {product.category_name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetail record={product} />
    </>
  );
}

ProductPage.getInitialProps = async (ctx: any) => {
  const res = await fetch(`${publicRuntimeConfig.apiUrl}/products/${ctx.query.id}`);
  const json = await res.json();

  return { product: json };
};

export default ProductPage;