import getConfig from 'next/config';
import Head from 'next/head';
import ProductThumbnail from '../components/ProductThumbnail';

const { publicRuntimeConfig } = getConfig();

declare interface HomeProps {
  products: IProduct[];
}

function Home(props: HomeProps) {
  const { products } = props || {};

  return (
    <>
      <Head>
        <title>Accessories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row">
        {(products || []).map((product) => (
          <ProductThumbnail key={product.id} record={product} />
        ))}
      </div>
    </>
  );
}

Home.getInitialProps = async () => {
  const res = await fetch(publicRuntimeConfig.apiUrl + '/products');
  const json = await res.json();

  return { products: json };
};

export default Home;
